### ISSUE TITLE
no VS-catppuccin-theme.vsix

### ISSUE THREAD

**Issue by RandomOtter** [Cutwell/VS-catppuccin-theme#5]
Hey 

VS-catppuccin-theme.vsix is nowhere to be found :P

**Comment by RandomOtter** [comment]
Hey 

VS-catppuccin-theme.vsix is nowhere to be found :P

**Comment by Cutwell** [comment]
Ah my mistake, updated the release.

It can be found in `Catppuccin.zip` https://github.com/Cutwell/VS-catppuccin-theme/releases/tag/v1.0
